Repository prgrms-fe-devcourse/FEDC4_Campers_Jaeho, pull requests merged in 2023-10, with the labels that each got.

#313 feat: 로그인이나 회원가입 실패시 이메일 항목으로 focusing
  src/components/SignIn.tsx
  src/components/SignUp.tsx
Labels: feature

#315 chore: husky pre-push에 build 명령어 추가
  .husky/pre-push
Labels: chore

#317 refactor: 디테일, 메인페이지, 유저프로파일 및 css 개선
  src/apis/poster.ts
  src/apis/search.ts
  src/assets/images/content_empty.png
  src/components/NavigationBar.tsx
  src/components/Post/MoreText.tsx
  src/components/Search/SearchBar.tsx
  src/components/Search/UserCard.tsx
  src/components/UserProfile/NotificationCard.tsx
  src/components/Weather.tsx
  src/components/common/AbsoluteCenterBox.tsx
  src/components/common/CircleIconBg.tsx
  src/components/common/DarkMode.tsx
  src/components/common/Loading.tsx
  src/components/common/NoResult.tsx
  src/components/common/PrimaryAvatar.tsx
  src/components/common/PrimaryButton.tsx
  src/components/common/PrimaryHeader.tsx
  src/components/common/PrimaryImage.tsx
  src/components/common/RecommendButton.tsx
  src/components/common/UploadImage.tsx
  src/hooks/mutation/usePost.ts
  src/hooks/mutation/useRecommend.ts
  src/hooks/query/useMainPageRender.ts
  src/hooks/useObserver.tsx
  src/pages/CreatePost.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/pages/Search.tsx
  src/pages/UserList.tsx
  src/pages/UserProfile.tsx
Labels: refactor

#319 refactor: location caching 5분으로 리펙토링
  src/hooks/query/useWeather.ts
Labels: refactor

#326 fix: useColorModeValue 및 Input의 bgColor 제거
  src/components/Auth/AuthInputFieldWithForm.tsx
Labels: fix

#321 feat: MoreText에 '줄이기' 추가, 변수명 변경
  src/components/Post/MoreText.tsx
Labels: fix

#323 fix: content-empty 이미지 경로 수정 및 VITE_MAIN_CHANNELID import 방식 수정
  index.html
  src/pages/Main.tsx
Labels: feature, fix

#327 fix: DarkMode에서 ThemeToggle로 이름 변경, theme style 관련 정리
  src/components/ThemeToggle.tsx
  src/pages/Main.tsx
  src/theme/index.ts
Labels: feature, fix
