Repository prgrms-fe-devcourse/FEDC4_Campers_Jaeho, pull requests merged in 2023-09, with the labels that each got.

#9 feat: 필수 라이브러리 설치 및 설정
  package.json
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: chore

#11 feat: 폴더 구조 설정
  .commitlintrc.json
  src/App.css
  src/App.tsx
  src/apis/.empty
  src/components/.empty
  src/components/common/.empty
  src/constants/.empty
  src/contexts/.empty
  src/hooks/.empty
  src/index.css
  src/main.tsx
  src/pages/.empty
  src/types/.empty
  src/utils/.empty
Labels: chore

#13 chore: commitlint 추가 설정(header-max-length, body-empty)
  .commitlintrc.json
Labels: chore

#17 feat: 라우터 구조 정의
  src/App.tsx
  src/constants/.empty
  src/constants/routes.ts
  src/main.tsx
Labels: feature

#20 fix: jsxImportSource의 @emotion/react 설정 제거
  tsconfig.json
  vite.config.ts
Labels: fix

#18 feat: 색상 변수 정의
  src/theme/globalConfig.ts
Labels: feature

#25 feat: global 테마 초기 세팅 추가 및 커스텀(colors) 일시 주석
  src/main.tsx
  src/theme/globalConfig.ts
  src/theme/index.ts
Labels: feature

#27 feat: axios 인스턴스 정의
  src/apis/axios.ts
Labels: feature

#29 feat: 로그인, 회원가입 경로 통합
  src/App.tsx
  src/constants/routes.ts
  src/pages/.empty
  src/pages/Auth.tsx
Labels: feature

#32 chore: chakra icons 설치
  package.json
  yarn.lock
Labels: chore

#30 feat: 회원,인증 axios 로직 정의
  .env.example
  .gitignore
  src/apis/auth.ts
  src/apis/axios.ts
  src/utils/storage.ts
Labels: feature

#35 feat: Auth 페이지 컴포넌트 디자인
  src/apis/.empty
  src/pages/Auth.tsx
  src/utils/.empty
Labels: feature, chore

#38 fix: mw에서 maxW로 수정 및 colors 삭제
  src/theme/index.ts
Labels: bug, fix

#40 feat: 회원가입(signup) 컴포넌트, Auth 공통 컴포넌트 생성
  src/components/.empty
  src/components/SignUp.tsx
  src/components/common/.empty
  src/components/common/Auth/AuthButton.tsx
  src/pages/Auth.tsx
  src/utils/passwordValidation.ts
Labels: feature, refactor

#41 feat: 로그인(Login) 페이지 컴포넌트 생성
  src/components/Login.tsx
  src/pages/Auth.tsx
Labels: feature

#43 feat: encode util 함수 추가
  src/apis/poster.ts
  src/utils/encode.ts
Labels: feature

#47 chore: uuid 라이브러리 설치
  package.json
  yarn.lock
Labels: chore

#48 refactor: Auth 관련 컴포넌트들(SignUp, SingIn) 상수(변수) 개명, 훅으로 대체
  src/components/Login.tsx
  src/components/SignIn.tsx
  src/components/SignUp.tsx
  src/pages/Auth.tsx
Labels: feature, refactor

#51 refactor: AuthButton을 PrimaryButton으로 개명 및 로직 변경
  src/components/SignIn.tsx
  src/components/SignUp.tsx
  src/components/common/Auth/AuthButton.tsx
  src/components/common/PrimaryButton.tsx
Labels: refactor

#57 refactor: Auth(SignUp, SignIn)의 Input 공통화 컴포넌트(AuthInputField) 생성 및 적용
  src/components/Auth/AuthInputField.tsx
  src/components/SignIn.tsx
  src/components/SignUp.tsx
Labels: feature, refactor

#58 feat: NotFound(404) 페이지 컴포넌트 생성
  src/App.tsx
  src/assets/images/not_found.png
  src/pages/NotFound.tsx
Labels: feature

#55 feat: BottomNavBar 컴포넌트 구현
  src/App.tsx
  src/components/BottomNavBar.tsx
  src/components/ContentList.tsx
  src/components/MainPageContent.tsx
  src/hooks/useObserver.tsx
  src/pages/Main.tsx
Labels: feature, fix

#46 feat: search axios 로직 정의
  src/apis/search.ts
Labels: feature

#63 chore: @chakra-ui/icons 한계 극복을 위한 react-icons 설치
  package.json
  yarn.lock
Labels: chore

#69 feat: avatarImage 컴포넌트 생성
  src/components/common/AvatarImage.tsx
Labels: feature

#79 refactor: AvatarImage의 props 정리, PrimaryAvatar로 개명
  src/components/common/AvatarImage.tsx
  src/components/common/PrimaryAvatar.tsx
Labels: refactor

#68 feat: Like 컴포넌트 정의
  src/components/common/Like.tsx
Labels: feature

#70 feat: TemperatureBar 컴포넌트 생성
  src/components/common/TemperatureBar.tsx
Labels: feature

#59 feat: 포스트 생성 컴포넌트 구현
  src/App.tsx
  src/apis/poster.ts
  src/components/CreatePost.tsx
  src/pages/Create.tsx
Labels: feature, refactor

#88 refactor: search axios params 변경
  src/apis/search.ts
Labels: refactor

#93 fix: Like에서 RecommendButton으로 개명 후 로직 변경
  src/components/common/Like.tsx
  src/components/common/RecommendButton.tsx
Labels: fix

#75 feat: PrimaryLink 컴포넌트 생성
  src/components/common/PrimaryLink.tsx
Labels: feature

#98 feat: NavigationBar 컴포넌트 Main페이지에 정의
  src/components/NavigationBar.tsx
  src/pages/Main.tsx
Labels: feature

#99 fix: BottonNavbar 컴포넌트 삭제
  src/components/BottomNavBar.tsx
Labels: feature

#71 feat: MoreText 컴포넌트 생성
  src/components/Post/MoreText.tsx
  src/components/common/TemperatureBar.tsx
Labels: feature

#103 feat: UserProfile 페이지 제작
  src/App.tsx
  src/apis/search.ts
  src/components/UserInfo.tsx
  src/components/common/UserInfoItem.tsx
  src/constants/routes.ts
  src/main.tsx
  src/pages/UserProfile.tsx
Labels: feature, refactor

#108 refactor: auth 관련 type, api 생성 및 개선
  src/apis/auth.ts
  src/apis/axios.ts
  src/types/.empty
  src/types/auth.ts
  src/types/user.ts
Labels: feature, refactor

#112 fix: axiosInterface가 instance로 바뀌면서 발생하는 오류 개선
  src/apis/poster.ts
  src/apis/search.ts
Labels: fix

#110 feat: Auth 내부 SignIn, SignUp에 api 연결 및 예외 처리
  src/components/SignIn.tsx
  src/components/SignUp.tsx
Labels: feature

#115 feat: 로그인이 완료된 후의 Auth로 페이지 이동 막기
  src/components/SignIn.tsx
  src/components/SignUp.tsx
  src/pages/Auth.tsx
Labels: feature

#116 refactor: AuthInputFieldWithForm으로 개명 및 로직 정리
  src/components/Auth/AuthInputField.tsx
  src/components/Auth/AuthInputFieldWithForm.tsx
  src/components/SignIn.tsx
  src/components/SignUp.tsx
Labels: refactor

#118 fix: 잘못된 import 경로 변경 및 오타 수정
  src/apis/axios.ts
  src/hooks/.empty
  src/pages/Main.tsx
Labels: fix

#120 chore: @tanstack/react-query-devtools dev로 설치
  package.json
  yarn.lock
Labels: chore

#123 fix: Mainpage 축소시 데이터 로드 중지 되는 버그 수정
  src/components/ContentList.tsx
Labels: fix

#121 feat: 친구목록 Page 레이아웃 정의
  src/App.tsx
  src/pages/User.tsx
Labels: feature

#131 feat: PrimaryText 컴포넌트 정의
  src/components/common/PrimaryText.tsx
Labels: feature

#125 feat: 포스트 검색 페이지 제작
  src/App.tsx
  src/apis/search.ts
  src/assets/images/search.png
  src/components/Search/SearchBar.tsx
  src/components/Search/SearchResponse/NoResult.tsx
  src/components/Search/SearchResponse/PostCard.tsx
  src/components/Search/SearchResponse/UserCard.tsx
  src/components/Search/SearchResponse/index.tsx
  src/components/Search/index.tsx
  src/components/common/PrimaryAvatar.tsx
  src/components/common/UserInfoItem.tsx
  src/constants/routes.ts
  src/hooks/useSearch.ts
  src/pages/Search.tsx
  src/types/post.ts
  src/types/user.ts
Labels: feature, refactor, style

#136 feat: user axios 로직 정의/search axios 수정
  src/apis/search.ts
  src/apis/user.ts
Labels: feature

#134 refactor: 마이페이지(User Info) 컴포넌트 및 페이지 구조 리팩토링
  src/apis/search.ts
  src/components/common/GridList.tsx
  src/components/common/PrimaryLink.tsx
  src/components/common/UploadImage.tsx
  src/pages/UserProfile.tsx
Labels: feature, refactor

#139 chore: return 전에 줄바꿈하는 eslint 규칙 추가
  .eslintrc.cjs
Labels: chore

#144 feat: User에 관련된react-query 훅 정의
  src/hooks/useQueryUser.tsx
Labels: feature

#145 refactor: useQueryPost 훅 정의 및 axios나 타입 코드 정리
  src/apis/poster.ts
  src/apis/search.ts
  src/apis/user.ts
  src/components/CreatePost.tsx
  src/components/UserInfo.tsx
  src/components/common/UploadImage.tsx
  src/components/common/UserInfoItem.tsx
  src/hooks/useQueryPost.tsx
  src/pages/UserProfile.tsx
  src/types/user.ts
Labels: feature, refactor

#150 fix: searchPoster 경로 수정
  src/pages/Detail.tsx
Labels: fix

#152 refactor: ComponentProps를 활용하여 PrimaryButton 확장
  src/components/common/PrimaryButton.tsx
Labels: refactor

#153 refactor: Search 페이지 컴포넌트 페이지 단 분리
  src/App.tsx
  src/components/Search/PostCard.tsx
  src/components/Search/SearchBar.tsx
  src/components/Search/SearchResponse/NoResult.tsx
  src/components/Search/SearchResponse/index.tsx
  src/components/Search/UserCard.tsx
  src/components/Search/index.tsx
  src/components/common/Loading.tsx
  src/components/common/NoResult.tsx
  src/components/common/PrimaryInfo.tsx
  src/pages/Search.tsx
  src/pages/UserProfile.tsx
Labels: feature, refactor

#157 feat: Auth의 alert을 chakra ui의 Alert Dialog로 교체
  src/components/SignIn.tsx
  src/components/SignUp.tsx
  src/components/common/PrimaryAlertDialogSet.tsx
Labels: feature

#158 feat: User page 기능 구현
  src/components/common/PrimaryList.tsx
  src/hooks/useFilter.tsx
  src/pages/User.tsx
  src/pages/UserList.tsx
Labels: feature

#164 fix: router 추가/로그아웃 되는 훅 주석 처리 / useFilter 리펙토링
  src/App.tsx
  src/apis/user.ts
  src/hooks/useQueryUser.tsx
Labels: fix

#161 refactor: CreatePost 페이지 파일 구조 리팩토링 및 query 훅 사용
  src/App.tsx
  src/components/CreatePost.tsx
  src/components/common/UploadImage.tsx
  src/pages/Create.tsx
  src/pages/CreatePost.tsx
Labels: refactor

#167 chore: query 파일 구조 정의
  src/hooks/apis/Mutation/index.ts
  src/hooks/apis/Query/index.ts
Labels: chore

#170 feat: useAuthCheck hook 생성
  src/hooks/useAuthCheck.ts
Labels: feature

#172 feat: PrimaryButton padding 좌우 반응형 추가
  src/components/common/PrimaryButton.tsx
Labels: feature

#175 feat: 후기 작성을 위한 생성포스터 페이지 / axios 정의
  src/apis/poster.ts
  src/pages/CreatePost.tsx
Labels: feature

#176 feat: Auth(SignIn , SingUp) 디자인 추가
  src/components/Auth/AuthInputFieldWithForm.tsx
  src/components/SignIn.tsx
  src/components/SignUp.tsx
  src/pages/Auth.tsx
Labels: feature

#159 refactor: MainpageContent , ContentList리팩터링
  src/apis/channelPosts.ts
  src/assets/images/no_image.png
  src/components/ContentList.tsx
  src/components/Main/MainPageContent.tsx
  src/components/Main/MainPagePosts.tsx
  src/components/PostGridList.tsx
  src/hooks/useObserver.tsx
  src/pages/Main.tsx
Labels: refactor

#188 bug: .env의 파일 변수 오타로 재설정
  .env.example
  src/components/Main/MainPagePosts.tsx
Labels: bug, chore, fix

#190 feat: userInfo 관련 Provider 생성
  src/apis/auth.ts
  src/contexts/.empty
  src/contexts/UserInfoProvider.tsx
  src/main.tsx
Labels: feature, fix

#192 fix: filterData 변수명 수정
  src/pages/UserList.tsx
Labels: fix

#197 fix: useFilter 훅 추가 및 main 수정
  .env.example
  src/hooks/useFilter.tsx
  src/main.tsx
Labels: bug, fix

#203 feat: ReactQueryDevtools main에 추가
  src/main.tsx
Labels: feature

#198 feat: post에 관련된 react-query 정의
  src/apis/poster.ts
  src/apis/social.ts
  src/components/common/NoResult.tsx
  src/hooks/mutation/useCreatePost.ts
  src/hooks/query/useDetailPost.ts
  src/hooks/query/usePostsByChannel.ts
  src/hooks/query/useSearchAll.ts
  src/hooks/useQueryPost.tsx
  src/pages/CreatePost.tsx
  src/pages/Search.tsx
  src/types/post.ts
Labels: feature, refactor

#96 feat: comment create axios구현
  src/apis/comment.ts
Labels: feature

#193 feat: axios 단에서 main페이지 JSON으로 나오는 데이터 처리
  src/apis/search.ts
  src/utils/titleValidation.ts
Labels: feature

#206 refactor: navigation bar user Profile 경로 수정
  src/components/NavigationBar.tsx
Labels: refactor

#191 refactor: 기타 확장을 위한 컴포넌트 스타일 변경
  src/components/Main/MainPagePosts.tsx
  src/components/NavigationBar.tsx
  src/components/PostCard.tsx
  src/components/PostGridList.tsx
  src/components/Search/UserCard.tsx
  src/components/common/CircleIconBg.tsx
  src/components/common/Comment.tsx
  src/components/common/PrimaryAvatar.tsx
  src/components/common/PrimaryButton.tsx
  src/components/common/PrimaryGrid.tsx
  src/components/common/PrimaryList.tsx
  src/components/common/PrimaryText.tsx
  src/components/common/TemperatureBar.tsx
  src/components/common/UploadImage.tsx
  src/constants/routes.ts
  src/pages/CreatePost.tsx
  src/pages/Main.tsx
  src/pages/Search.tsx
  src/pages/UserProfile.tsx
Labels: refactor

#208 fix: env 변수명 수정
  src/components/Main/MainPagePosts.tsx
Labels: bug

#142 feat: 유저페이지에서 알림모달창 구현
  src/apis/Notification.ts
  src/components/common/PrimaryModal.tsx
  src/pages/UserProfile.tsx
Labels: feature, fix

#201 feat: PrimaryTabsSet 공통 컴포넌트 생성 및 적용
  src/components/common/PrimaryTabsSet.tsx
  src/pages/Auth.tsx
  src/pages/UserList.tsx
Labels: feature, refactor

#211 bug: userPapge 렌더 버그
  src/hooks/query/useNotification.ts
  src/pages/UserProfile.tsx
Labels: bug

#215 Feature/214 detail hooks
  src/apis/comment.ts
  src/hooks/mutation/useComment.ts
Labels: feature

#216 feat: useFilter 훅에 context 정보 추가
  src/hooks/useFilter.tsx
Labels: feature

#218 feat: 팔로우/팔로잉에 관한 훅/axios/type 정의
  src/apis/Notification.ts
  src/hooks/mutation/useHandleNotification.ts
  src/types/social.ts
Labels: feature

#221 feat: 동물 이미지 추가
  src/assets/images/avatar_bear.jpg
  src/assets/images/avatar_dear.jpg
  src/assets/images/avatar_frog.jpg
  src/assets/images/avatar_penguin.jpg
  src/assets/images/avatar_rabbit.jpg
  src/assets/images/avatar_tiger.jpg
Labels: feature

#223 Feat/#209 comments optimistic update
  src/apis/poster.ts
  src/components/common/Comment.tsx
  src/components/common/InputForm.tsx
  src/components/common/PrimaryAvatar.tsx
  src/components/common/PrimaryButton.tsx
  src/hooks/mutation/useRecommend.ts
  src/hooks/query/useDetailPost.ts
  src/pages/Detail.tsx
Labels: feature

#226 feat: 무한스크롤 useInfinitQuery 로 변경
  src/apis/search.ts
  src/components/Main/MainPagePosts.tsx
  src/hooks/query/useMainPageRender.ts
  src/hooks/query/usePostsByChannel.ts
  src/pages/Main.tsx
Labels: feature

#225 feat: userProfile 페이지 수정이나 로그아웃 등 기능 부착
  src/apis/Notification.ts
  src/components/common/PrimaryImage.tsx
  src/components/common/UploadImage.tsx
  src/hooks/mutation/useChangeUserInfo.ts
  src/hooks/mutation/useLogout.ts
  src/hooks/query/useLogout.ts
  src/hooks/query/useNotification.ts
  src/pages/UserProfile.tsx
  src/utils/isSameUser.ts
Labels: feature, refactor

#229 refactor: userInfo 페이지에 사용하기 위해 axios단에 image 데이터 추가
  src/apis/search.ts
Labels: refactor

#230 Feat/##209 comments optimistic update
  src/components/common/RecommendButton.tsx
  src/hooks/mutation/useRecommend.ts
  src/pages/Detail.tsx
Labels: fix

#233 feat: Main 페이지 및 내부 컴포넌트 스타일 수정
  src/components/NavigationBar.tsx
  src/pages/Main.tsx
Labels: feature

#240 feat: userInfo 관련 context 수정 및 관련 파일 변경
  src/apis/auth.ts
  src/components/NavigationBar.tsx
  src/components/SignIn.tsx
  src/components/SignUp.tsx
  src/contexts/UserInfoProvider.tsx
  src/hooks/useFilter.tsx
  src/pages/UserProfile.tsx
  src/utils/storage.ts
Labels: feature, bug, style, fix

#242 feat: Auth에 이전 버튼 추가 및 helperText 단어 단위로 줄바꿈 속성 추가
  src/components/Auth/AuthInputFieldWithForm.tsx
  src/components/common/PrimaryLink.tsx
  src/pages/Auth.tsx
Labels: feature

#236 Bug/#235 댓글 낙관적 업데이트, 이미지 누락 버그 수정
  src/apis/comment.ts
  src/apis/poster.ts
  src/apis/search.ts
  src/apis/social.ts
  src/components/common/Comment.tsx
  src/components/common/InputForm.tsx
  src/hooks/mutation/useComment.ts
  src/hooks/query/useDetailPost.ts
  src/pages/Detail.tsx
Labels: bug

#232 feat: userProfile 페이지에서 팔로우, 언팔로우 처리
  src/App.tsx
  src/apis/Notification.ts
  src/apis/social.ts
  src/apis/user.ts
  src/components/common/PrimaryImage.tsx
  src/hooks/mutation/useChangeUserInfo.ts
  src/hooks/mutation/useFollow.ts
  src/hooks/query/useNotification.ts
  src/hooks/query/useSearchUser.ts
  src/pages/UserProfile.tsx
  src/types/user.ts
Labels: feature

#244 feat: PrimatyAlertDialogSet에 확인, 취소 실행시 동작 추가 및 UerProfile의 logout, Sign에 적용
  src/components/SignIn.tsx
  src/components/SignUp.tsx
  src/components/common/PrimaryAlertDialogSet.tsx
  src/pages/UserProfile.tsx
Labels: feature

#249 fix: userProfile 페이지 context 구조 변경
  src/apis/user.ts
  src/hooks/mutation/useChangeUserInfo.ts
  src/pages/UserProfile.tsx
  src/utils/encode.ts
Labels: fix

#258 bug: Mainpage render fix, 로그인 버튼 확대
  src/components/NavigationBar.tsx
  src/components/common/CircleIconBg.tsx
  src/components/common/PrimaryButton.tsx
  src/pages/Auth.tsx
  src/pages/Main.tsx
Labels: fix

#250 feat: weather에 관련된 axios/훅 정의
  .env.example
  src/apis/weather.ts
  src/hooks/query/useWeather.ts
  src/hooks/useLocation.ts
Labels: feature

#262 fix: PostCard 임포트 및 타입수정
  src/components/PostCard.tsx
Labels: bug

#264 fix: 안쓰는 파일 제거
  src/components/common/PrimaryAvatar.tsx
  src/components/common/PrimaryList.tsx
Labels: fix

#266 feat: 비오는 애니메이션 구현
  src/components/common/Rain.tsx
Labels: feature

#267 Fix/#260 post card import type fix 와 너비 리팩터
  src/components/NavigationBar.tsx
  src/components/common/PrimaryContainer.tsx
  src/components/common/PrimaryHeader.tsx
  src/pages/CreatePost.tsx
  src/pages/Main.tsx
  src/pages/Search.tsx
  src/pages/UserProfile.tsx
Labels: refactor, fix

#281 feat: 다크 모드 적용
  src/components/common/DarkMode.tsx
  src/components/common/PrimaryInfo.tsx
  src/pages/Main.tsx
Labels: feature

#271 Feat/#270 user list move search page
  src/components/Search/SearchBar.tsx
  src/components/Search/UserCard.tsx
  src/components/common/PrimaryInfo.tsx
  src/hooks/useFilter.tsx
  src/pages/Search.tsx
  src/pages/UserList.tsx
Labels: feature, refactor

#282 feat: main 페이지에 weather 컴포넌트 정의
  src/assets/images/not_user.png
  src/assets/images/rain.png
  src/assets/images/snow.png
  src/assets/images/warm.png
  src/components/Weather.tsx
  src/components/common/Rain.tsx
  src/pages/Main.tsx
  src/utils/FilterWeatherText.ts
Labels: feature

#285 refactor: 다크모드 아이콘으로 수정 및 커스텀 로고 부착
  src/assets/images/Campers.png
  src/components/common/DarkMode.tsx
  src/components/common/PrimaryInfo.tsx
  src/pages/Main.tsx
Labels: refactor

#287 refactor: 다크모드 아이콘 색깔 변경
  src/components/NavigationBar.tsx
Labels: refactor

#288 Refactor/#283 weather css 수정
  src/components/PostCard.tsx
  src/components/Weather.tsx
  src/components/common/PrimaryContainer.tsx
Labels: refactor

#275 feat: UserProfile에 이미지 낙관적 업데이트 추가
  src/pages/UserProfile.tsx
Labels: feature

#277 feat: Search를 고려한 PrimaryTabsSet 변경 및 적용
  src/components/common/PrimaryTabsSet.tsx
  src/pages/Search.tsx
Labels: feature

#290 refactor: 다크모드가 적용되지 않는 부분 수정
  src/components/Auth/AuthInputFieldWithForm.tsx
  src/components/Weather.tsx
  src/components/common/CircleIconBg.tsx
  src/components/common/PrimaryHeader.tsx
  src/components/common/PrimaryTabsSet.tsx
  src/pages/Auth.tsx
  src/pages/UserProfile.tsx
Labels: refactor

#279 feat: CreatePost에서 제목 focusing, PrimaryAlertDialog 추가
  src/apis/poster.ts
  src/hooks/useTimeout.ts
  src/pages/CreatePost.tsx
Labels: feature, refactor

#297 fix: comment comp fix
  src/apis/Comment.tsx
  src/components/common/Comment.tsx
  src/components/common/RecommendButton.tsx
  src/pages/Detail.tsx
Labels: bug

#295 refactor: 다크 모드 적용 안된 부분들 머지 후 수정
  src/components/NavigationBar.tsx
  src/components/common/Loading.tsx
  src/hooks/mutation/useCreatePost.ts
  src/hooks/query/useNotification.ts
  src/pages/CreatePost.tsx
  src/pages/Main.tsx
  src/pages/Search.tsx
  src/pages/UserProfile.tsx
Labels: refactor, fix

#299 fix: Comment 파일 삭제
  src/apis/Comment.tsx
Labels: fix

#301 fix: 포스트 생성페이지 훅 최상단에 선언이 안된 버그 수정
  src/pages/CreatePost.tsx
Labels: bug, fix

#303 refactor: 호버 시 이상해지는 버튼 제거
  src/pages/Detail.tsx
Labels: refactor

#305 style: 버튼 컬러 white로 변경
  src/components/common/PrimaryHeader.tsx
Labels: style

#309 fix: ui 수정
  src/components/NavigationBar.tsx
  src/components/common/CircleIconBg.tsx
  src/components/common/DarkMode.tsx
  src/components/common/PrimaryHeader.tsx
  src/components/common/RecommendButton.tsx
  src/pages/Detail.tsx
  src/pages/Main.tsx
  src/pages/UserProfile.tsx
Labels: fix

#311 chore: vercel.json 추가
  vercel.json
Labels: chore
